export const INTERACTIVE_GAMES = [
  {
    key: 'whoAmongUs', icon: '👥', color: '#5F7D6C', seconds: 0, competitive: false,
    ar: { name: 'مين فينا؟', players: '3 لاعبين فأكثر', description: 'اختاروا الشخص الذي تنطبق عليه العبارة أكثر.', how: 'اقرؤوا العبارة ثم يشير الجميع في الوقت نفسه إلى اختيارهم. الهدف هو الضحك والتعارف، ولا توجد إجابات صحيحة أو عقوبات.' },
    en: { name: 'Who Among Us?', players: '3+ players', description: 'Vote for the person who best matches the prompt.', how: 'Read the prompt, then everyone points at the same time. It is for laughs and connection—there are no wrong answers or penalties.' },
    items: [
      { ar: 'مين فينا يتذكر التفاصيل الصغيرة أكثر؟', en: 'Who remembers small details best?' },
      { ar: 'مين فينا يمكنه تعلّم مهارة جديدة بسرعة؟', en: 'Who could learn a new skill fastest?' },
      { ar: 'مين فينا يعرف أفضل أماكن الطعام؟', en: 'Who knows the best food spots?' },
      { ar: 'مين فينا يحافظ على هدوئه وقت الضغط؟', en: 'Who stays calmest under pressure?' },
      { ar: 'مين فينا قد يبدأ مشروعًا مفيدًا للمجتمع؟', en: 'Who might start a project that helps the community?' },
      { ar: 'مين فينا ينجح في تنظيم رحلة جماعية؟', en: 'Who would organize a group trip best?' },
      { ar: 'مين فينا يكتشف حل اللغز أولًا؟', en: 'Who would solve a mystery first?' },
      { ar: 'مين فينا يضحك الآخرين دون أن يقصد؟', en: 'Who makes others laugh without trying?' },
      { ar: 'مين فينا يمكن أن يكتب كتابًا يومًا ما؟', en: 'Who could write a book one day?' },
      { ar: 'مين فينا لديه أقوى ذاكرة للأسماء؟', en: 'Who has the best memory for names?' },
      { ar: 'مين فينا يجيد شرح الأشياء الصعبة ببساطة؟', en: 'Who explains difficult things most simply?' },
      { ar: 'مين فينا يلاحظ التغيير في المكان أولًا؟', en: 'Who notices changes in a room first?' },
    ],
  },
  {
    key: 'actGuess', icon: '🎭', color: '#9A3B4B', seconds: 45, competitive: true,
    ar: { name: 'مثّل وخمّن', players: '4 لاعبين فأكثر', description: 'مثّل الكلمة بصمت ودع فريقك يخمّنها.', how: 'يرى الممثل البطاقة وحده ثم يبدأ الوقت. يمنع الكلام أو إصدار أصوات تدل على الكلمة. كل تخمين صحيح نقطة.' },
    en: { name: 'Act & Guess', players: '4+ players', description: 'Act out the word silently while your team guesses.', how: 'Only the actor sees the card, then starts the timer. No speaking or clue sounds. Each correct guess earns a point.' },
    items: [
      { ar: 'بطريق يمشي', en: 'A walking penguin' },
      { ar: 'رائد فضاء', en: 'An astronaut' },
      { ar: 'فتح هدية كبيرة', en: 'Opening a huge gift' },
      { ar: 'البحث عن مفتاح ضائع', en: 'Looking for a lost key' },
      { ar: 'طباخ يقلب فطيرة', en: 'A chef flipping a pancake' },
      { ar: 'شخص يحاول التقاط صورة جماعية', en: 'Taking a group photo' },
      { ar: 'قطة تطارد ضوءًا', en: 'A cat chasing a light' },
      { ar: 'قيادة سيارة في شارع مزدحم', en: 'Driving through heavy traffic' },
      { ar: 'زراعة شجرة', en: 'Planting a tree' },
      { ar: 'اكتشاف كنز', en: 'Discovering treasure' },
      { ar: 'الاستيقاظ متأخرًا', en: 'Waking up late' },
      { ar: 'محاولة فتح مرطبان', en: 'Trying to open a jar' },
    ],
  },
  {
    key: 'trueFalse', icon: '🔬', color: '#3F718C', seconds: 0, competitive: true, reveal: true,
    ar: { name: 'حقيقة أم خرافة؟', players: 'لاعبان فأكثر', description: 'خمنوا هل المعلومة صحيحة ثم اكشفوا التفسير.', how: 'يصوّت كل لاعب قبل كشف الإجابة. تحتسب نقطة لكل إجابة صحيحة، واقرؤوا التفسير القصير لتتعلموا معلومة جديدة.' },
    en: { name: 'Fact or Myth?', players: '2+ players', description: 'Decide whether the statement is true, then reveal why.', how: 'Everyone votes before revealing the answer. Award one point for each correct vote and read the short explanation together.' },
    items: [
      { ar: 'للأخطبوط ثلاثة قلوب.', en: 'An octopus has three hearts.', answerAr: 'حقيقة', answerEn: 'Fact', noteAr: 'يضخ قلبان الدم إلى الخياشيم، بينما يضخه الثالث إلى بقية الجسم.', noteEn: 'Two pump blood to the gills, while the third pumps it around the body.' },
      { ar: 'نستخدم 10% فقط من أدمغتنا.', en: 'We use only 10% of our brains.', answerAr: 'خرافة', answerEn: 'Myth', noteAr: 'تعمل مناطق مختلفة من الدماغ في أوقات ومهام مختلفة، ولا توجد 90% خاملة.', noteEn: 'Different brain regions work across different tasks; 90% is not simply unused.' },
      { ar: 'الصوت لا ينتقل في فراغ الفضاء.', en: 'Sound cannot travel through the vacuum of space.', answerAr: 'حقيقة', answerEn: 'Fact', noteAr: 'الصوت يحتاج إلى مادة مثل الهواء أو الماء لتنقل الاهتزازات.', noteEn: 'Sound needs matter, such as air or water, to carry vibrations.' },
      { ar: 'يمكن رؤية سور الصين العظيم بوضوح من القمر.', en: 'The Great Wall of China is clearly visible from the Moon.', answerAr: 'خرافة', answerEn: 'Myth', noteAr: 'هو ضيق جدًا مقارنة بالمسافة ولا يُرى بالعين المجردة من القمر.', noteEn: 'It is far too narrow relative to the distance to be seen unaided from the Moon.' },
      { ar: 'العسل يمكن أن يبقى صالحًا مدة طويلة جدًا إذا حُفظ جيدًا.', en: 'Honey can remain edible for a very long time when stored well.', answerAr: 'حقيقة', answerEn: 'Fact', noteAr: 'قلة الماء والحموضة تساعدان على منع نمو كثير من الميكروبات.', noteEn: 'Its low moisture and acidity inhibit the growth of many microbes.' },
      { ar: 'الخفافيش عمياء تمامًا.', en: 'Bats are completely blind.', answerAr: 'خرافة', answerEn: 'Myth', noteAr: 'الخفافيش تستطيع الرؤية، وتستخدم أنواع كثيرة منها تحديد الموقع بالصدى أيضًا.', noteEn: 'Bats can see, and many species also use echolocation.' },
      { ar: 'بعض الأشجار أقدم من الأهرامات.', en: 'Some living trees are older than the pyramids.', answerAr: 'حقيقة', answerEn: 'Fact', noteAr: 'تعيش بعض أشجار الصنوبر المعمّرة آلاف السنين.', noteEn: 'Some bristlecone pines have lived for thousands of years.' },
      { ar: 'تغيّر الحرباء لونها فقط لتختبئ.', en: 'Chameleons change color only for camouflage.', answerAr: 'خرافة', answerEn: 'Myth', noteAr: 'يتغير اللون أيضًا للتواصل وتنظيم الحرارة والاستجابة للمزاج.', noteEn: 'Color also changes for communication, temperature control, and social signals.' },
      { ar: 'الماء الساخن يتجمد دائمًا أسرع من الماء البارد.', en: 'Hot water always freezes faster than cold water.', answerAr: 'خرافة', answerEn: 'Myth', noteAr: 'قد يحدث ذلك في ظروف محددة، لكنه ليس قاعدة دائمة.', noteEn: 'It can happen under particular conditions, but it is not a universal rule.' },
      { ar: 'اليوم على كوكب الزهرة أطول من سنته.', en: 'A day on Venus is longer than its year.', answerAr: 'حقيقة', answerEn: 'Fact', noteAr: 'دوران الزهرة حول نفسه أبطأ من دورانه حول الشمس.', noteEn: 'Venus rotates on its axis more slowly than it orbits the Sun.' },
    ],
  },
  {
    key: 'guessChoice', icon: '🤔', color: '#786B9C', seconds: 0, competitive: true,
    ar: { name: 'خمن اختياري', players: '3 لاعبين فأكثر', description: 'اختر إجابتك سرًا ودع الآخرين يتوقعونها.', how: 'يختار لاعب بين الخيارين دون أن يخبر أحدًا. يتوقع الباقون اختياره، ثم يكشفه ويشرح السبب. يحصل من خمن صحيحًا على نقطة.' },
    en: { name: 'Guess My Choice', players: '3+ players', description: 'Choose secretly and let everyone predict your answer.', how: 'One player secretly picks A or B. Everyone predicts the choice, then the player reveals it and explains why. Correct guesses earn a point.' },
    items: [
      { ar: 'رحلة إلى البحر أم إلى الجبال؟', en: 'A trip to the sea or the mountains?', aAr: 'البحر', bAr: 'الجبال', aEn: 'Sea', bEn: 'Mountains' },
      { ar: 'تعلّم لغة جديدة أم آلة موسيقية؟', en: 'Learn a new language or a musical instrument?', aAr: 'لغة', bAr: 'آلة موسيقية', aEn: 'Language', bEn: 'Instrument' },
      { ar: 'قراءة الكتاب أم مشاهدة الفيلم؟', en: 'Read the book or watch the film?', aAr: 'الكتاب', bAr: 'الفيلم', aEn: 'Book', bEn: 'Film' },
      { ar: 'التخطيط المبكر أم القرار العفوي؟', en: 'Plan early or decide spontaneously?', aAr: 'التخطيط', bAr: 'العفوية', aEn: 'Plan', bEn: 'Spontaneity' },
      { ar: 'زيارة الماضي أم رؤية المستقبل؟', en: 'Visit the past or see the future?', aAr: 'الماضي', bAr: 'المستقبل', aEn: 'Past', bEn: 'Future' },
      { ar: 'مدينة كبيرة أم قرية هادئة؟', en: 'A big city or a quiet village?', aAr: 'المدينة', bAr: 'القرية', aEn: 'City', bEn: 'Village' },
      { ar: 'قدرة الطيران أم التنفس تحت الماء؟', en: 'Fly or breathe underwater?', aAr: 'الطيران', bAr: 'تحت الماء', aEn: 'Fly', bEn: 'Underwater' },
      { ar: 'عمل جماعي أم عمل فردي؟', en: 'Teamwork or working alone?', aAr: 'جماعي', bAr: 'فردي', aEn: 'Team', bEn: 'Solo' },
      { ar: 'صباح نشيط أم سهرة هادئة؟', en: 'An active morning or a calm evening?', aAr: 'الصباح', bAr: 'المساء', aEn: 'Morning', bEn: 'Evening' },
      { ar: 'متحف علوم أم محمية طبيعية؟', en: 'A science museum or a nature reserve?', aAr: 'متحف العلوم', bAr: 'المحمية', aEn: 'Science museum', bEn: 'Nature reserve' },
    ],
  },
  {
    key: 'findConnection', icon: '🔗', color: '#557C83', seconds: 0, competitive: true, reveal: true,
    ar: { name: 'ما الرابط؟', players: 'لاعبان فأكثر', description: 'اكتشفوا الفكرة التي تجمع الكلمات الأربع.', how: 'اقرؤوا الكلمات معًا. أول لاعب أو فريق يكتشف الرابط يشرح إجابته ثم يكشف الحل ويحصل على نقطة.' },
    en: { name: 'Find the Connection', players: '2+ players', description: 'Discover the idea connecting all four words.', how: 'Read the four words together. The first player or team to explain the connection reveals the answer and earns a point.' },
    items: [
      { ar: 'شمس • شمعة • مصباح • برق', en: 'Sun • Candle • Lamp • Lightning', answerAr: 'كلها مصادر للضوء', answerEn: 'They are all sources of light', noteAr: 'بعضها طبيعي وبعضها من صنع الإنسان.', noteEn: 'Some are natural and some are human-made.' },
      { ar: 'جذر • ساق • ورقة • زهرة', en: 'Root • Stem • Leaf • Flower', answerAr: 'أجزاء النبات', answerEn: 'Parts of a plant', noteAr: 'لكل جزء وظيفة تساعد النبات على الحياة والتكاثر.', noteEn: 'Each part helps the plant live and reproduce.' },
      { ar: 'مقياس حرارة • ساعة • مسطرة • ميزان', en: 'Thermometer • Clock • Ruler • Scale', answerAr: 'أدوات للقياس', answerEn: 'Tools used for measuring', noteAr: 'تقيس الحرارة والوقت والطول والكتلة.', noteEn: 'They measure temperature, time, length and mass.' },
      { ar: 'ذاكرة • انتباه • لغة • تعلّم', en: 'Memory • Attention • Language • Learning', answerAr: 'وظائف معرفية للدماغ', answerEn: 'Cognitive functions of the brain', noteAr: 'تتعاون شبكات متعددة في الدماغ لإنجازها.', noteEn: 'Multiple brain networks work together to support them.' },
      { ar: 'مطر • نهر • بحر • سحابة', en: 'Rain • River • Sea • Cloud', answerAr: 'دورة الماء', answerEn: 'The water cycle', noteAr: 'ينتقل الماء باستمرار بين الأرض والغلاف الجوي.', noteEn: 'Water continually moves between Earth and the atmosphere.' },
      { ar: 'نحل • فراشة • طائر • خفاش', en: 'Bee • Butterfly • Bird • Bat', answerAr: 'قد تساعد كلها في التلقيح', answerEn: 'All can act as pollinators', noteAr: 'ينقل بعضها حبوب اللقاح بين الأزهار.', noteEn: 'Some carry pollen from flower to flower.' },
      { ar: 'خريطة • بوصلة • نجوم • نظام تحديد المواقع', en: 'Map • Compass • Stars • GPS', answerAr: 'وسائل لمعرفة الاتجاه والموقع', answerEn: 'Ways to navigate and locate', noteAr: 'تجمع بين أدوات قديمة وتقنيات حديثة.', noteEn: 'They span ancient tools and modern technology.' },
      { ar: 'إعادة استخدام • إصلاح • تدوير • تقليل', en: 'Reuse • Repair • Recycle • Reduce', answerAr: 'طرق لتقليل النفايات', answerEn: 'Ways to reduce waste', noteAr: 'الأفضل غالبًا تقليل الاستهلاك قبل الحاجة إلى التدوير.', noteEn: 'Reducing consumption often comes before recycling.' },
    ],
  },
  {
    key: 'whatHappens', icon: '🧪', color: '#A35E45', seconds: 0, competitive: true, reveal: true,
    ar: { name: 'ماذا سيحدث؟', players: 'لاعبان فأكثر', description: 'توقعوا نتيجة موقف علمي أو حياتي ثم اكتشفوا السبب.', how: 'اختاروا الإجابة قبل كشف النتيجة. كل توقع صحيح نقطة، والأهم قراءة التفسير ومناقشة السبب.' },
    en: { name: 'What Happens Next?', players: '2+ players', description: 'Predict the result of a science or everyday situation.', how: 'Choose an answer before revealing the result. Each correct prediction earns a point; then read and discuss the explanation.' },
    items: [
      { ar: 'ماذا يحدث لظل جسم عندما نقرّبه من مصدر الضوء؟', en: 'What happens to an object’s shadow as it moves closer to a light source?', optionsAr: ['يكبر', 'يصغر', 'يختفي دائمًا'], optionsEn: ['It grows', 'It shrinks', 'It always disappears'], answerAr: 'يكبر غالبًا', answerEn: 'It usually grows', noteAr: 'يحجب الجسم زاوية أكبر من الضوء عندما يقترب من المصدر.', noteEn: 'The object blocks a wider angle of light when closer to the source.' },
      { ar: 'أي قطعة ثلج تذوب أسرع: فوق معدن أم فوق خشب في الغرفة نفسها؟', en: 'Which ice cube melts faster: one on metal or one on wood in the same room?', optionsAr: ['المعدن', 'الخشب', 'بالسرعة نفسها دائمًا'], optionsEn: ['Metal', 'Wood', 'Always the same'], answerAr: 'فوق المعدن غالبًا', answerEn: 'Usually the one on metal', noteAr: 'المعدن ينقل حرارة الغرفة إلى الثلج أسرع من الخشب.', noteEn: 'Metal transfers room heat to the ice faster than wood.' },
      { ar: 'إذا زرعنا نبتة قرب نافذة من جهة واحدة، كيف تنمو غالبًا؟', en: 'If a plant receives window light from one side, how will it usually grow?', optionsAr: ['نحو الضوء', 'بعيدًا عن الضوء', 'إلى الأسفل'], optionsEn: ['Toward the light', 'Away from the light', 'Downward'], answerAr: 'نحو الضوء', answerEn: 'Toward the light', noteAr: 'تُسمّى هذه الاستجابة الانتحاء الضوئي.', noteEn: 'This response is called phototropism.' },
      { ar: 'ماذا يحدث للصوت عندما نبتعد عن مصدره؟', en: 'What happens to a sound as we move farther from its source?', optionsAr: ['يضعف عادة', 'يقوى دائمًا', 'لا يتغير'], optionsEn: ['It usually weakens', 'It always grows louder', 'It does not change'], answerAr: 'يضعف عادة', answerEn: 'It usually weakens', noteAr: 'تنتشر طاقة الموجة الصوتية على مساحة أكبر.', noteEn: 'The sound wave’s energy spreads over a larger area.' },
      { ar: 'إذا وضعنا ورقة جافة في الماء، ماذا يحدث أولًا؟', en: 'What happens first when dry paper is placed in water?', optionsAr: ['تمتص الماء', 'تتحول إلى زجاج', 'تطفو للأبد دون تغير'], optionsEn: ['It absorbs water', 'It turns to glass', 'It floats forever unchanged'], answerAr: 'تمتص الماء', answerEn: 'It absorbs water', noteAr: 'تدخل المياه في الفراغات الدقيقة بين ألياف الورق.', noteEn: 'Water enters tiny spaces between the paper fibres.' },
      { ar: 'ماذا يحدث لمعدل التنفس غالبًا بعد الجري؟', en: 'What usually happens to breathing rate after running?', optionsAr: ['يزداد', 'يتوقف', 'ينخفض فورًا'], optionsEn: ['It increases', 'It stops', 'It drops immediately'], answerAr: 'يزداد', answerEn: 'It increases', noteAr: 'يحتاج الجسم إلى مزيد من الأكسجين والتخلص من ثاني أكسيد الكربون.', noteEn: 'The body needs more oxygen and must remove more carbon dioxide.' },
    ],
  },
  {
    key: 'ifWriter', icon: '✍️', color: '#7B5A45', seconds: 0, competitive: false,
    ar: { name: 'لو كنت كاتبًا…', players: 'لاعبان فأكثر', description: 'تخيّل قصة عن الموضوع الظاهر واحكِ بدايتها أو نهايتها.', how: 'يقرأ اللاعب البطاقة ويأخذ لحظة للتفكير، ثم يروي بداية القصة أو نهايتها في دقيقة تقريبًا. يمكن للباقين إضافة سؤال واحد يوسّع الفكرة.' },
    en: { name: 'If You Were a Writer…', players: '2+ players', description: 'Imagine a story about the prompt and tell its beginning or ending.', how: 'Read the card, take a moment to think, then tell the beginning or ending in about a minute. The group may ask one question that expands the idea.' },
    items: [
      { ar: 'لو كتبت قصة عن مدينة لا ينام سكانها، كيف ستبدأ؟', en: 'If you wrote about a city whose people never sleep, how would it begin?' },
      { ar: 'لو كتبت قصة عن رسالة وصلت بعد مئة عام، ماذا ستكون نهايتها؟', en: 'If you wrote about a letter delivered one hundred years late, how would it end?' },
      { ar: 'لو كتبت قصة عن طفل يفهم لغة الحيوانات، كيف ستبدأ؟', en: 'If you wrote about a child who understands animals, how would it begin?' },
      { ar: 'لو كتبت قصة عن مكتبة تختفي كل صباح، ماذا ستكون نهايتها؟', en: 'If you wrote about a library that disappears every morning, how would it end?' },
      { ar: 'لو كتبت قصة عن آخر شجرة في المدينة، كيف ستبدأ؟', en: 'If you wrote about the last tree in a city, how would it begin?' },
      { ar: 'لو كتبت قصة عن ساعة تعيد خمس دقائق فقط، ماذا ستكون نهايتها؟', en: 'If you wrote about a clock that rewinds only five minutes, how would it end?' },
      { ar: 'لو كتبت قصة عن عائلة وجدت خريطة داخل كتاب قديم، كيف ستبدأ؟', en: 'If you wrote about a family finding a map inside an old book, how would it begin?' },
      { ar: 'لو كتبت قصة عن روبوت يريد تعلّم الضحك، ماذا ستكون نهايتها؟', en: 'If you wrote about a robot learning to laugh, how would it end?' },
      { ar: 'لو كتبت قصة عن قرية تتبدل أماكن بيوتها ليلًا، كيف ستبدأ؟', en: 'If you wrote about a village whose houses move at night, how would it begin?' },
      { ar: 'لو كتبت قصة عن رحلة لا يعرف ركابها وجهتها، ماذا ستكون نهايتها؟', en: 'If you wrote about a journey whose passengers do not know the destination, how would it end?' },
      { ar: 'لو كتبت قصة عن عالم اكتشف لونًا جديدًا، كيف ستبدأ؟', en: 'If you wrote about a scientist discovering a new colour, how would it begin?' },
      { ar: 'لو كتبت قصة عن باب لا يفتح إلا عند قول الحقيقة، ماذا ستكون نهايتها؟', en: 'If you wrote about a door that opens only when someone tells the truth, how would it end?' },
      { ar: 'لو كتبت قصة عن يوم اختفت فيه كل الشاشات، كيف ستبدأ؟', en: 'If you wrote about a day when every screen stopped working, how would it begin?' },
      { ar: 'لو كتبت قصة عن جزيرة تظهر يومًا واحدًا كل سنة، ماذا ستكون نهايتها؟', en: 'If you wrote about an island that appears one day each year, how would it end?' },
      { ar: 'لو كتبت قصة عن صديقين وجدا بذرة مضيئة، كيف ستبدأ؟', en: 'If you wrote about two friends finding a glowing seed, how would it begin?' },
      { ar: 'لو كتبت قصة عن متحف تتحدث معروضاته ليلًا، ماذا ستكون نهايتها؟', en: 'If you wrote about museum exhibits that talk at night, how would it end?' },
    ],
  },
  {
    key: 'storyMaker', icon: '🎬', color: '#6F4D73', seconds: 0, competitive: false,
    ar: { name: 'صانع القصة', players: '3 لاعبين فأكثر', description: 'ولّدوا عناصر عشوائية وألّفوا قصة أو سيناريو يجمعها.', how: 'يولّد التطبيق ستة عناصر. يمكنكم تغيير عنصر واحد بالضغط عليه أو تغييرها كلها. يضيف كل شخص جزءًا من القصة، ويجب أن تظهر جميع العناصر قبل النهاية.' },
    en: { name: 'Story Maker', players: '3+ players', description: 'Generate random ingredients and create one story or screenplay.', how: 'The app generates six ingredients. Tap one to replace it or change them all. Each person adds part of the story, and every ingredient must appear before the ending.' },
    items: [{ ar: 'ألّفوا قصة تجمع كل العناصر الآتية.', en: 'Create a story using every ingredient below.' }],
    parts: [
      { key: 'place', labelAr: 'المكان', labelEn: 'Place', ar: ['مكتبة مهجورة', 'قطار يعبر الصحراء', 'جزيرة عائمة', 'مرصد قديم', 'مدرسة بعد الغروب', 'مدينة تحت الماء', 'بيت فوق جبل', 'متحف ليلًا', 'مخبز صغير', 'قرية كثيرة الضباب'], en: ['An abandoned library', 'A train crossing the desert', 'A floating island', 'An old observatory', 'A school after sunset', 'An underwater city', 'A house on a mountain', 'A museum at night', 'A tiny bakery', 'A foggy village'] },
      { key: 'time', labelAr: 'الزمن', labelEn: 'Time', ar: ['الوقت الحاضر', 'بعد مئة عام', 'قبل خمسين عامًا', 'ليلة شتوية', 'أول يوم في الصيف', 'قبل شروق الشمس', 'يوم توقف فيه الزمن', 'خلال أربع وعشرين ساعة', 'في زمن قديم', 'يوم يتكرر باستمرار'], en: ['The present day', 'One hundred years from now', 'Fifty years ago', 'A winter night', 'The first day of summer', 'Before sunrise', 'A day when time stops', 'Within twenty-four hours', 'An ancient time', 'A day that keeps repeating'] },
      { key: 'theme', labelAr: 'ثيم القصة', labelEn: 'Theme', ar: ['الصداقة', 'الاكتشاف', 'الشجاعة', 'التعاون', 'العائلة', 'الأمل', 'حماية الطبيعة', 'حب المعرفة', 'المسؤولية', 'تقبّل الاختلاف'], en: ['Friendship', 'Discovery', 'Courage', 'Cooperation', 'Family', 'Hope', 'Protecting nature', 'Love of knowledge', 'Responsibility', 'Accepting differences'] },
      { key: 'plot', labelAr: 'الحبكة', labelEn: 'Plot', ar: ['تصل رسالة بلا اسم مرسل', 'يعثر الأبطال على خريطة ناقصة', 'يختفي شيء مهم من المكان', 'تظهر شخصية تدّعي أنها من المستقبل', 'يكتشفون غرفة لم يلاحظها أحد', 'تصلهم مهمة لا يستطيع شخص واحد إنجازها', 'يجدون جهازًا لا يعرفون وظيفته', 'يتلقون دعوة إلى مكان غير موجود على الخريطة', 'يستيقظ الجميع بمهارة جديدة', 'يكتشفون أن قصة قديمة كانت حقيقية'], en: ['A letter arrives with no sender', 'The heroes find an incomplete map', 'Something important vanishes', 'Someone claims to be from the future', 'They discover a room nobody noticed', 'They receive a task no one can finish alone', 'They find a device with an unknown purpose', 'They are invited to a place missing from every map', 'Everyone wakes with a new ability', 'They learn an old tale was true'] },
      { key: 'conflict', labelAr: 'العقدة', labelEn: 'Conflict', ar: ['الوقت ينفد', 'يختلف الفريق حول القرار الصحيح', 'الدليل الأهم مفقود', 'عاصفة تمنعهم من العودة', 'لا أحد يصدق ما شاهدوه', 'عليهم الاختيار بين هدفين مهمين', 'تتعطل الأداة الوحيدة التي يحتاجونها', 'يفهمون الدليل بطريقة خاطئة', 'يجب أن يساعدوا شخصًا كان يعارضهم', 'يكتشفون أن الحل يغيّر خطتهم كلها'], en: ['Time is running out', 'The team disagrees on the right decision', 'The most important clue is missing', 'A storm blocks the way home', 'Nobody believes what they saw', 'They must choose between two important goals', 'Their only useful tool breaks', 'They misunderstand the clue', 'They must help someone who opposed them', 'The solution changes their entire plan'] },
      { key: 'ending', labelAr: 'النهاية', labelEn: 'Ending', ar: ['نهاية سعيدة غير متوقعة', 'نهاية مفتوحة لسؤال جديد', 'يعود كل شيء إلى البداية بمعنى مختلف', 'يكتشفون أن الرحلة كانت أهم من الجائزة', 'يحل الفريق المشكلة بالتعاون', 'تظهر حقيقة تغيّر فهم القصة', 'يعود الغرض المفقود إلى صاحبه', 'تبدأ مغامرة جديدة فورًا', 'يختار البطل قرارًا لم يتوقعه أحد', 'تكشف آخر جملة سرًا صغيرًا'], en: ['An unexpectedly happy ending', 'An open ending with a new question', 'Everything returns to the beginning with new meaning', 'The journey matters more than the prize', 'The team solves it together', 'A truth changes the meaning of the story', 'The lost object returns to its owner', 'A new adventure begins immediately', 'The hero makes an unexpected choice', 'The final line reveals a small secret'] },
    ],
  },
];

export function interactiveGame(key) {
  return INTERACTIVE_GAMES.find((game) => game.key === key);
}
